import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex bg-white">
      <div className="w-[13%] md:w-[9%] lg:w-[19%] xl:w-[15%] p-3">
        <Link
          href="/"
          className="flex justify-center lg:justify-start items-center"
        >
          <Image
            src="/logo.png"
            alt="logo"
            width="32"
            height="32"
            className="min-h-8"
          />
          <span className="hidden lg:block text-lg font-extrabold text-blue-800">
            eeworks
          </span>
        </Link>
        <Menu />
      </div>
      <div className="w-[87%] md:w-[91%] lg:w-[81%] xl:w-[85%] bg-slate-100 flex flex-col overflow-y-scroll scrollbar">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
