export const SUBJECTS = [
  "Mathematics",
  "English Language",
  "Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Social Studies",
  "History",
  "Geography",
  "Civics",
  "Literature in English",
  "French",
  "Spanish",
  "German",
  "Mandarin",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Swahili",
  "Integrated Science",
  "Computer Science",
  "ICT",
  "Environmental Science",
  "Agricultural Science",
  "Health Science",
  "Commerce",
  "Accounting",
  "Economics",
  "Business Studies",
  "Entrepreneurship",
  "Fine Arts",
  "Music",
  "Drama",
  "Theatre Arts",
  "Dance",
  "Home Economics",
  "Technical Drawing",
  "Woodwork",
  "Metalwork",
  "Electronics",
  "Physical Education (PE)",
  "Sports Science",
  "Personal Health and Fitness",
  "Sex Education",
  "Further Mathematics",
  "Statistics",
  "Astronomy",
  "Psychology",
  "Media Studies",
  "Design and Technology",
];

export const lt20Words = [
  "",
  "One",
  "Two",
  "Three",
  "Four",
  "Five",
  "Six",
  "Seven",
  "Eight",
  "Nine",
  "Ten",
  "Eleven",
  "Twelve",
  "Thirteen",
  "Fourteen",
  "Fifteen",
  "Sixteen",
  "Seventeen",
  "Eighteen",
  "Nineteen",
];
export const get20Words = [
  "",
  "",
  "Twenty",
  "Thirty",
  "Forty",
  "Fifty",
  "Sixty",
  "Seventy",
  "Eighty",
  "Ninety",
];
